backend:
  name: github
  repo: MiBE85/seomanden-site # dit eget GitHub repo
  branch: main
  base_url: https://decap-cms-oauth.deno.dev
  auth_endpoint: auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: "https://beautiful-gecko-00d95b.netlify.app"
display_url: "https://beautiful-gecko-00d95b.netlify.app"

collections:
  - name: "pages"
    label: "Sider"
    files:
      - label: "Forside"
        name: "index"
        file: "index.html"
        editor:
          preview: false
      - label: "Ydelser"
        name: "ydelser"
        file: "ydelser.html"
        editor:
          preview: false
      - label: "Kontakt"
        name: "kontakt"
        file: "kontakt.html"
        editor:
          preview: false
      - label: "Referencer"
        name: "referencer"
        file: "referencer.html"
        editor:
          preview: false
