backend:
  name: git-gateway
  branch: main
  identity_url: https://beautiful-gecko-00d95b.netlify.app/.netlify/identity
  gateway_url: https://beautiful-gecko-00d95b.netlify.app/.netlify/git
media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: "https://beautiful-gecko-00d95b.netlify.app"
display_url: "https://beautiful-gecko-00d95b.netlify.app"

collections:
  - name: "pages"
    label: "Sider"
    files:
      - label: "Forside"
        name: "index"
        file: "index.html"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Indhold", name: "body", widget: "text" }

      - label: "Ydelser"
        name: "ydelser"
        file: "ydelser.html"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Indhold", name: "body", widget: "text" }

      - label: "Kontakt"
        name: "kontakt"
        file: "kontakt.html"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Indhold", name: "body", widget: "text" }

      - label: "Referencer"
        name: "referencer"
        file: "referencer.html"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Indhold", name: "body", widget: "text" }
